version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - gu install native-image
      - echo PWD 1 is `pwd`
      - cd lambda
      - echo PWD 2 is `pwd`
      - java -jar /lein/leiningen-2.9.3-standalone.jar -m leiningen.core.main uberjar
      - native-image -jar target/output.jar --report-unsupported-elements-at-runtime --no-fallback --verbose --enable-url-protocols=http,https --no-server  --initialize-at-build-time --initialize-at-build-time=org.apache.log4j.CategoryKey --trace-object-instantiation=java.lang.Thread

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/output.jar

