AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "NLQuiz lambda functions using `holy-lambda` micro library"
Parameters:
  Runtime:
    Type: String
    Default: java8
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 2000
Globals:
  Function:
    Runtime: !Ref Runtime
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
Resources:
  GenerateNL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlquiz-lambda.core.GenerateNL
      CodeUri: target/output.jar
      FunctionName: GenerateNL
      Events:
        Event:
          Type: Api
          Properties:
            Path: /generate
            Method: get
  GenerateWithAltsNL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlquiz-lambda.core.GenerateWithAltsNL
      CodeUri: target/output.jar
      FunctionName: GenerateWithAltsNL
      Events:
        Event:
          Type: Api
          Properties:
            Path: /generate-with-alts
            Method: get
  ParseNL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: nlquiz-lambda.core.ParseNL
      CodeUri: target/output.jar
      FunctionName: ParseNL
      Events:
        Event:
          Type: Api
          Properties:
            Path: /parse
            Method: get

